### PR TITLE
build: generate types for release

### LINKED ISSUE #19: 🚀 Feature: Add types
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-tools/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Type declarations should be published.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by RebeccaStevens**
## PR Checklist

- [x] Addresses an existing open issue: fixes #19
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/ts-api-tools/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/ts-api-tools/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Generate types on `build:release`.

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Right! Thanks! 🙌

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Ah, but the `package.json` sorting needs to happen. Could you fix the lint issues real quick please?

```plaintext
/home/runner/work/ts-api-tools/ts-api-tools/package.json
Error:   44:4  error  Expected object keys to be in ascending order. 'import' should be before 'types'  jsonc/sort-keys
Error:   54:2  error  Expected object keys to be in ascending order. 'name' should be before 'types'    jsonc/sort-keys
```

**Comment by RebeccaStevens** [comment]
One of those linting issue can't be fixed. `types` must come before any other field in `exports`.

I don't think sorting `package.json` fields alphabetically is good idea. We should instead us an approach like in #22

**Comment by JoshuaKGoldberg** [comment]
> `types` must come before any other field in exports.

...huh, TIL (thanks!). I'll admit I haven't set this up before. Do you have a good resource that describes this?

**Comment by RebeccaStevens** [comment]
> Do you have a good resource that describes this?

Have a look at this: https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing

**Comment by JoshuaKGoldberg** [comment]
> Entry-point for TypeScript resolution - must occur first!

Ryan Reynolds in surgical gear going "but why?"

I guess this is blocked on https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/223. 😩

**Review by JoshuaKGoldberg — APPROVED** [review]
❤️‍🔥

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @RebeccaStevens for bug

**Comment by RebeccaStevens** [comment]
> > Entry-point for TypeScript resolution - must occur first!
> 
> Ryan Reynolds in surgical gear going "but why?"

I imagine the reason is because when looking for a matching pattern for the path, `import` is also a valid match as types are imported (`require` might be to in certain contexts, maybe?). We need to have types first so that types always resolve to types and not JS.

**Pull request merged**
